@startwbs
!include plantuml.puml

* 単子葉植物
** ショウブ目
*** ショウブ科
**** ショウブ属
***** ショウブ
** キジカクシ目
*** アヤメ科
**** アヤメ属
***** アヤメ
***** カキツバタ
***** シャガ
**** サフラン属
**** フリージア属
*** ラン科
*** ヒガンバナ科
** ユリ目
*** ユリ科
**** ユリ属
***** ヤマユリ
***** オニユリ
**** チューリップ属
***** チューリップ
**** カタクリ属
***** カタクリ
@endwbs
